### ISSUE TITLE
Additional Input utilities

### ISSUE THREAD

**Issue by kyle-downey** [jon-hanson/parsecj#11]
It would be useful to support Input types based on Reader and with some kind of pluggable Scanner. The specific use case is skipping comments: you cannot really achieve this today because everything takes String -- certain functions presume CharInput, which is package-private, so you cannot really implement your own Input for this -- and so for instance the reported position won't include the comment characters.

I am working around this by writing a factory utility that creates an Input and scans to build a String under the covers, but as noted the error handling is still not quite right with this approach.

**Comment by jon-hanson** [comment]
Hmmm, that could be tricky. The `attempt` combinator allows backtracking to any previous point in the input stream, up to and including the very beginning. Consequently, any stream-based Input would have to store each token from the entire input stream in a random-access container. As such, you might as well read the stream into a container before constructing an Input.

**Comment by kyle-downey** [comment]
How about just making CharInput public in 0.4? I understand the concerns about allowing arbitrary Input sequences but it's cleaner if developers can plug in their own classes (e.g. using mmap file or just putting in custom logic for scanning). 

Right now it's package-private and other parts of the code check for it, so you are pretty much forced to use Input.of() factory methods only.

**Comment by jon-hanson** [comment]
Ok, done. Please take a look and let me know if the latest changes help.

**Comment by kyle-downey** [comment]
Looks good. Are you cutting 0.4 soon? If not I'll do a local build for testing until it's available.
