### ISSUE TITLE
Support for recursive grammars

### ISSUE THREAD

**Issue by wqsz7xn** [jon-hanson/parsecj#18]
Forgive me if my parsec knowledge is a very rusty. I haven't worked with it in quite a while.
Is there any way to work around recursive grammars with this library? I'm attempting to create a [graphvis parser](https://graphviz.org/doc/info/lang.html) and am trying to implement the `a_list` parser which has the following grammar:

a_list | : | ID '=' ID [ (';' \| ',') ] [ a_list ]
-- | -- | --

usually in parsec i can be self referential in my parser definitions:

```haskell
list :: Parser (List Int)
list = cons <|> nil
  where
    cons = Cons <$> (decimal <* endOfLine) <*> list
    nil  = pure Nil 
```
([source here)](https://stackoverflow.com/a/14674408)

but with java I'm meeting a limitation where you can't exactly self reference variable definitions
```java
final static Parser<Character, Array> parser = [can't reference parser here like I can in haskell]
```
Some guidance would be much appreciated!

**Comment by wqsz7xn** [comment]
```java
       // E ::= 'x' | 'a' E 'b'
        Parser.Ref<Character, String> e = Parser.ref();

        Parser<Character, String> aEb = (Parser<Character, String>) string("a").bind(a -> e.then(string("b").bind((b -> retn( a + b )))));
        e.set(string("x").or(aEb));
        System.out.println(e.parse(Input.of("aaxbb")).getResult())
```
seems I was able to get something working afterall from the funj library. I probably should have built on that anyways.

**Comment by jon-hanson** [comment]
Both Parsecj and the funcj.parser provide a lazy reference type (`Ref`).
