### ISSUE TITLE
javafp organization?

### ISSUE THREAD

**Issue by jbgi** [jon-hanson/parsecj#2]
not an issue but I thought you might want to create/own the javafp organization on github. I had previously created this github organization for a project of mine but then saw that you already owned the domain name, so I changed to another organization name.

**Comment by jon-hanson** [comment]
Thanks for the heads-up and apologies for nicking the domain name before you! I've created the organisation, though I've never used them before. Is there any advantage?

**Comment by jbgi** [comment]
In the early stage, not much advantages, but once a project become popular (many contributors, web site...) it's harder to switch, and also it may also be confusing if someone else own the github organization.
