### ISSUE TITLE
Optional return UNIT

### ISSUE THREAD

**Issue by yeyan** [jon-hanson/parsecj#4]
Combinator optional should return a Maybe like type (util.Option, or something provided by the library itself) rather than return Unit

**Comment by jon-hanson** [comment]
If you require an `Optional` value then the `optionalOpt` combinator returns a parser for an `Optional` value.

I decided to make the `optional` parser return `Unit` to follow the convention taken by the [Haskell Parsec library](https://hackage.haskell.org/package/parsec-3.1.11/docs/Text-Parsec-Combinator.html).

**Comment by yeyan** [comment]
Thanks for the clarification, therefor I assume optional is all about side effects then.

**Comment by jon-hanson** [comment]
The intent  is that you would use `optional` where you are not interested in the parse result - all you want the parser to do is to detect it and step over it. For example, if you were parsing a +ve digit, then you might accept either `n` or `+n` (where `n` is a digit), e.g. `8` or `+8`. If your parser encounters a `+` then you don't need the result, so you would use `optional` to step over it:

`optional(chr('+')).then(digit)`

**Comment by yeyan** [comment]
My case is a little bit different, I was trying to parse a URI which may or may not have a user login information supplied. If not supplied guest user will be implied, I tried with optional and side effect to achieve this, and the solution smells to me. But clearly I was pursuing the wrong combinator. Again thank you for the explanation, I will try with optionalOpt.
